// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdqbpiqqnzxypxypypph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkcWJwaXFxbnp4eXB4eXB5cHBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNTQzNDMsImV4cCI6MjA1NDkzMDM0M30.oNgtyJ8MfwVj-tknwk5DAFCq0Xf36Y6o6SZOsHP_Dmk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);